### PR TITLE
Fix EdmondsKarp max flow for directed and min cut source set for both directed/undirected graphs 

### LINKED ISSUE #1031: Fix getSourceSet of EdmonKarp max flow

### PR DESCRIPTION
**Pull request by CharJon**
See #1031.

### CODE REVIEW

File: networkit/cpp/flow/EdmondsKarp.cpp [hunk 1]
```diff
@@ -118,6 +118,15 @@ std::vector<node> EdmondsKarp::getSourceSet() const {
                 visited[v] = true;
             }
         });
+        if (graph->isDirected()) {
+            // Follow backwards edges in residual network
+            graph->forInNeighborsOf(u, [&](node, node v, edgeweight weight, edgeid eid) {
```
Comment (fabratu) [inline networkit/cpp/flow/EdmondsKarp.cpp:123]: I think you can use the signature `graph->forInNeighborsOf(u, [&](node, node v, edgeid eid)` here.

Comment (CharJon) [reply networkit/cpp/flow/EdmondsKarp.cpp]: Indeed, weight is unused. Done.

**Comment by CharJon** [comment]
I try to add some more testcases over the next days and remove the "Draft:" afterwards.

**Comment by fabratu** [comment]
Hm, for both of the new test instances the previous implementation of `getSourceSet` also works. Can you give an example or reason, why the function has to be modified to work for directed graphs?

**Comment by CharJon** [comment]
> Hm, for both of the new test instances the previous implementation of `getSourceSet` also works (in a sense, that we have a min cut for edges `(s,t)` with `s in Source` and `t not in Source`) . Can you give an example or reason, why the function has to be modified to work for directed graphs?

For the testcase "testEdmondsKarpDirected2" the original implementation reports {0,2,3} as the sourceSet. But the vertex partitioning {0,2,3}, {1,4} does not imply the min-cut of value 1. From my perspective this is not in line with what the docstring states "@return The set of nodes that form the (smallest) source side of the flow/minimum cut.". At least I as a user expected the function to return an actual partitioning corresponding to the min-cut. Is this not the intended functionality?

**Comment by CharJon** [comment]
I completely dismissed the undirected case in this PR, but a simliar problem seems to exist. If I'm not missing something, a more general fix is needed, instead of my !isDirected distinction. I added a directed version of "testEdmondsKarpDirected2" ("testEdmondsKarpP3") where again, the sourceSet does not yield the correct min-cut.

**Comment by CharJon** [comment]
@fabratu there seems to be an additional bug for directed input graphs. "testEdmondsKarpDirected7", which is a direct translation of a wikipedia example, fails. 

Do you prefer fixing the directed and undirected cases in one PR or in should two separated one be opened (or sth else)?

**Comment by fabratu** [comment]
> Do you prefer fixing the directed and undirected cases in one PR or should a separated one be opened (or sth else)?

I would prefer fixing this in one PR. I looked a bit deeper into the code and my previous comment was wrong indeed. Both the old implementation and your addition fail in some cases. For example, an undirected version of "testEdmondsKarpDirected2" would also fail currently.

Since the implementation tries to save memory for bookkeeping of the residual graph, I think we have to modify the tests in `getSourceSet` to also take into account backward edges. 

For undirected:

```
graph->forNeighborsOf(u, [&](node, node v, edgeweight weight, edgeid eid) {
            if (!visited[v] && ((u < v && flow[eid] < weight) || (u > v && flow[eid] > 0))) {
```

For directed: iterating like undirected + do the same tests for incoming neighbors.

**Comment by CharJon** [comment]
Okay, I try to implement fixes in the following order (if you agree):

1. Fix flow calculation for directed graphs, via case distinction (to make "testEdmondsKarpDirected7" pass
2. Fix / updated getSourceSet for undirected graphs

For 2.:  I'm not sure if your suggested fix works
```
graph->forNeighborsOf(u, [&](node, node v, edgeweight weight, edgeid eid) {
            if (!visited[v] && ((u < v && flow[eid] < weight) || (u > v && flow[eid] > 0))) {
```
The last line of the current run method
```
graph->parallelForEdges(
        [&](node, node, edgeid eid) { flow[eid] = std::max(flow[eid], residFlow[eid]); });
```
removes information about direction. But is this line really necessary anyways? Is there a clean definition of undirected flow, that makes it reasonable to take the max?
Also, while at it: I personally would like to rename the residFlow for undirected Graphs. Conceptually "flow" and "residFlow" store flow from u->v and v->u respectively for u <= v. Calling the second one "residualFlow" seems a bit missleading to me.

**Comment by CharJon** [comment]
Done. I tried to keep the new code close to the original one, but there might be room for improvement and some details might be worth to discuss?

- As in the undirected case I did not add any edges, but went with an implicit represenation of the residual network. This leads to a bunch of if/else blocks. Not sure if adding reverse edges would be better from a performance perspective
- To fix 2. from above I encoded the direction of flow via signs into the flow vector (this might be considered hacky, but I tried to avoid adding a member variable which would only be useful in the directed case)

File: networkit/cpp/flow/EdmondsKarp.cpp [hunk 2]
```diff
@@ -55,22 +56,125 @@ edgeweight EdmondsKarp::BFS(std::vector<edgeweight> &residFlow, std::vector<node
...
+    pred.resize(graph->upperNodeIdBound(), none);
+    std::vector<edgeweight> gain(graph->upperNodeIdBound(), std::numeric_limits<edgeweight>::max());
+
+    std::queue<node> Q;
+    Q.push(source);
+    pred[source] = source;
+    gain[source] = std::numeric_limits<edgeweight>::max();
+    ;
+
+    while (!Q.empty()) {
```
Comment (angriman) [inline networkit/cpp/flow/EdmondsKarp.cpp:71]: Nit: I suggest to change this with a `do { ... } while (!Q.empty());`. `Q` is never empty in the first iteration.

File: networkit/cpp/flow/EdmondsKarp.cpp [hunk 3]
```diff
@@ -55,22 +56,125 @@ edgeweight EdmondsKarp::BFS(std::vector<edgeweight> &residFlow, std::vector<node
...
+        node u = Q.front();
+        Q.pop();
+        bool sinkReached = false;
+
+        graph->forNeighborsOf(u, [&](node, node v, edgeweight weight, edgeid eid) {
```
Comment (angriman) [inline networkit/cpp/flow/EdmondsKarp.cpp:76]: This can be simplified with:
```cpp
for (node v : G->inNeighborRange(u))
  // ...
```
so that you do not have to check `sinkReached`.

File: networkit/cpp/flow/EdmondsKarp.cpp [hunk 4]
```diff
@@ -55,22 +56,125 @@ edgeweight EdmondsKarp::BFS(std::vector<edgeweight> &residFlow, std::vector<node
...
+                    weight - flow[eid] + (reverseEdges[eid] == none ? 0 : flow[reverseEdges[eid]]);
+                gain[v] = std::min(gain[u], residCapa);
+            }
+        });
+
+        if (sinkReached) {
+            return gain[sink];
+        }
+
+        graph->forInNeighborsOf(u, [&](node, node v, edgeid eid) {
```
Comment (angriman) [inline networkit/cpp/flow/EdmondsKarp.cpp:95]: As above.

File: networkit/cpp/flow/test/EdmondsKarpGTest.cpp [hunk 5]
```diff
@@ -38,6 +38,9 @@ TEST_F(EdmondsKarpGTest, testEdmondsKarpP1) {
     EXPECT_EQ(1, edKa.getFlow(5, 6));
 
     std::vector<node> sourceSet(edKa.getSourceSet());
+    for (auto u : sourceSet) {
+        std::cout << "u: " << u << std::endl;
+    }
```
Comment (angriman) [inline networkit/cpp/flow/test/EdmondsKarpGTest.cpp:43]: This was used for debugging right? If you don't need it anymore it should be removed.

File: networkit/cpp/flow/test/EdmondsKarpGTest.cpp [hunk 6]
```diff
@@ -49,6 +52,200 @@ TEST_F(EdmondsKarpGTest, testEdmondsKarpP1) {
...
+    G.addEdge(2, 4, 5);
+    G.addEdge(3, 5, 15);
+    G.addEdge(4, 5, 5);
+
+    G.indexEdges();
+
+    EdmondsKarp edKa(G, 0, 5);
+    edKa.run();
+
+    EXPECT_EQ(15, edKa.getMaxFlow()) << "max flow is not correct";
```
Comment (angriman) [inline networkit/cpp/flow/test/EdmondsKarpGTest.cpp:71]: `getMaxFlow` returns a double, I suggest to use `EXPECT_DOUBLE_EQ(15.0, ...);`

File: networkit/cpp/flow/test/EdmondsKarpGTest.cpp [hunk 7]
```diff
@@ -49,6 +52,200 @@ TEST_F(EdmondsKarpGTest, testEdmondsKarpP1) {
...
+    edKa.run();
+    EXPECT_EQ(1, edKa.getMaxFlow()) << "max flow is not correct";
+
+    std::vector<node> sourceSet(edKa.getSourceSet());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 0), sourceSet.end());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 1), sourceSet.end());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 2), sourceSet.end());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 3), sourceSet.end());
+
+    EXPECT_EQ(std::find(sourceSet.begin(), sourceSet.end(), 4), sourceSet.end());
```
Comment (angriman) [inline networkit/cpp/flow/test/EdmondsKarpGTest.cpp:93]: These checks can be simplified with appropriate [container matchers](https://github.com/google/googletest/blob/main/docs/reference/matchers.md#container-matchers). For example:
```cpp
EXPECT_THAT(sourceSet, ::testing::Contains(0));
```

Or maybe even better:
```cpp
EXPECT_THAT(sourceSet, UnorderedElementsAre({0, 1, 2, 3, 4}));
```

File: networkit/cpp/flow/test/EdmondsKarpGTest.cpp [hunk 8]
```diff
@@ -49,6 +52,200 @@ TEST_F(EdmondsKarpGTest, testEdmondsKarpP1) {
...
+    G.addEdge(0, 1);
+    G.addEdge(0, 2);
+    G.addEdge(1, 3);
+    G.addEdge(2, 3);
+    G.addEdge(3, 4);
+    G.indexEdges();
+
+    EdmondsKarp edKa(G, 0, 4);
+    edKa.run();
+    EXPECT_EQ(1, edKa.getMaxFlow()) << "max flow is not correct";
```
Comment (angriman) [inline networkit/cpp/flow/test/EdmondsKarpGTest.cpp:85]: As above.

File: networkit/cpp/flow/test/EdmondsKarpGTest.cpp [hunk 9]
```diff
@@ -49,6 +52,200 @@ TEST_F(EdmondsKarpGTest, testEdmondsKarpP1) {
...
+
+    EdmondsKarp edKa(G, 0, 3);
+    edKa.run();
+    EXPECT_EQ(15, edKa.getMaxFlow()) << "max flow is not correct";
+
+    std::vector<node> sourceSet(edKa.getSourceSet());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 0), sourceSet.end());
+    EXPECT_EQ(std::find(sourceSet.begin(), sourceSet.end(), 1),
+              std::find(sourceSet.begin(), sourceSet.end(), 2));
+    EXPECT_EQ(std::find(sourceSet.begin(), sourceSet.end(), 3), sourceSet.end());
```
Comment (angriman) [inline networkit/cpp/flow/test/EdmondsKarpGTest.cpp:113]: Ditto.

File: networkit/cpp/flow/test/EdmondsKarpGTest.cpp [hunk 10]
```diff
@@ -49,6 +52,200 @@ TEST_F(EdmondsKarpGTest, testEdmondsKarpP1) {
...
+    edKa.run();
+    EXPECT_EQ(1, edKa.getMaxFlow()) << "max flow is not correct";
+
+    std::vector<node> sourceSet(edKa.getSourceSet());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 0), sourceSet.end());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 1), sourceSet.end());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 2), sourceSet.end());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 3), sourceSet.end());
+
+    EXPECT_EQ(std::find(sourceSet.begin(), sourceSet.end(), 4), sourceSet.end());
```
Comment (angriman) [inline networkit/cpp/flow/test/EdmondsKarpGTest.cpp:135]: Ditto.

File: networkit/cpp/flow/test/EdmondsKarpGTest.cpp [hunk 11]
```diff
@@ -49,6 +52,200 @@ TEST_F(EdmondsKarpGTest, testEdmondsKarpP1) {
...
+    EXPECT_EQ(4, edKa.getMaxFlow()) << "max flow is not correct";
+
+    std::vector<node> sourceSet(edKa.getSourceSet());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 0), sourceSet.end());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 1), sourceSet.end());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 2), sourceSet.end());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 3), sourceSet.end());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 4), sourceSet.end());
+
+    EXPECT_EQ(std::find(sourceSet.begin(), sourceSet.end(), 8), sourceSet.end());
```
Comment (angriman) [inline networkit/cpp/flow/test/EdmondsKarpGTest.cpp:164]: Ditto.

File: networkit/cpp/flow/test/EdmondsKarpGTest.cpp [hunk 12]
```diff
@@ -49,6 +52,200 @@ TEST_F(EdmondsKarpGTest, testEdmondsKarpP1) {
...
+    G.addEdge(1, 0, 2);
+    G.indexEdges();
+
+    EdmondsKarp edKa(G, 8, 0);
+    edKa.run();
+    EXPECT_EQ(4, edKa.getMaxFlow()) << "max flow is not correct";
+
+    std::vector<node> sourceSet(edKa.getSourceSet());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 8), sourceSet.end());
+    EXPECT_EQ(std::find(sourceSet.begin(), sourceSet.end(), 0), sourceSet.end());
```
Comment (angriman) [inline networkit/cpp/flow/test/EdmondsKarpGTest.cpp:188]: Ditto.

File: networkit/cpp/flow/test/EdmondsKarpGTest.cpp [hunk 13]
```diff
@@ -49,6 +52,200 @@ TEST_F(EdmondsKarpGTest, testEdmondsKarpP1) {
...
+    G.addEdge(1, 0, 4.4);
+    G.indexEdges();
+
+    EdmondsKarp edKa(G, 3, 0);
+    edKa.run();
+    EXPECT_EQ(2.4, edKa.getMaxFlow()) << "max flow is not correct";
+
+    std::vector<node> sourceSet(edKa.getSourceSet());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 3), sourceSet.end());
+    EXPECT_EQ(std::find(sourceSet.begin(), sourceSet.end(), 0), sourceSet.end());
```
Comment (angriman) [inline networkit/cpp/flow/test/EdmondsKarpGTest.cpp:204]: Ditto.

File: networkit/cpp/flow/test/EdmondsKarpGTest.cpp [hunk 14]
```diff
@@ -49,6 +52,200 @@ TEST_F(EdmondsKarpGTest, testEdmondsKarpP1) {
...
+    G.addEdge(1, 0, 4.4);
+    G.indexEdges();
+
+    EdmondsKarp edKa(G, 3, 0);
+    edKa.run();
+    EXPECT_EQ(0, edKa.getMaxFlow()) << "max flow is not correct";
+
+    std::vector<node> sourceSet(edKa.getSourceSet());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 3), sourceSet.end());
+    EXPECT_EQ(std::find(sourceSet.begin(), sourceSet.end(), 0), sourceSet.end());
```
Comment (angriman) [inline networkit/cpp/flow/test/EdmondsKarpGTest.cpp:220]: Ditto.

File: networkit/cpp/flow/test/EdmondsKarpGTest.cpp [hunk 15]
```diff
@@ -49,6 +52,200 @@ TEST_F(EdmondsKarpGTest, testEdmondsKarpP1) {
...
+    G.addEdge(5, 6, 9);
+    G.indexEdges();
+
+    EdmondsKarp edKa(G, 0, 6);
+    edKa.run();
+    EXPECT_EQ(5, edKa.getMaxFlow()) << "max flow is not correct";
+
+    std::vector<node> sourceSet(edKa.getSourceSet());
+    EXPECT_NE(std::find(sourceSet.begin(), sourceSet.end(), 0), sourceSet.end());
+    EXPECT_EQ(std::find(sourceSet.begin(), sourceSet.end(), 6), sourceSet.end());
```
Comment (angriman) [inline networkit/cpp/flow/test/EdmondsKarpGTest.cpp:246]: Ditto.

File: networkit/cpp/flow/EdmondsKarp.cpp (hunk 3 above)
Comment (angriman) [reply networkit/cpp/flow/EdmondsKarp.cpp:76]: Actually that's not true, unfortunately neighbor iterators do not provide edge ids, so I'm afraid that we have to keep this loop as it is.

File: networkit/cpp/flow/test/EdmondsKarpGTest.cpp [hunk 16]
```diff
@@ -32,21 +33,196 @@ TEST_F(EdmondsKarpGTest, testEdmondsKarpP1) {
...
+
+    EdmondsKarp edKa(G, 0, 3);
+    edKa.run();
+    EXPECT_DOUBLE_EQ(15, edKa.getMaxFlow()) << "max flow is not correct";
+
+    std::vector<node> sourceSet(edKa.getSourceSet());
+    EXPECT_THAT(sourceSet, testing::Contains(0));
+    // either 1 and 2 are in the set or none
+    EXPECT_EQ(std::find(sourceSet.begin(), sourceSet.end(), 1),
+              std::find(sourceSet.begin(), sourceSet.end(), 2));
```
[the remark this answers is not in the document]
Comment (CharJon) [reply networkit/cpp/flow/test/EdmondsKarpGTest.cpp]: Was indeed not correct.

File: networkit/cpp/flow/EdmondsKarp.cpp [hunk 17]
```diff
@@ -6,7 +6,6 @@
  *              Michael Hamann <michael.hamann@kit.edu>
  */
 
-#include <algorithm>
```
[the remark this answers is not in the document]
Comment (CharJon) [reply networkit/cpp/flow/EdmondsKarp.cpp:9]: I fail to see where and my IDE tells me to remove it, but I added it again.

File: networkit/cpp/flow/EdmondsKarp.cpp [hunk 18]
```diff
@@ -27,17 +26,76 @@ edgeweight EdmondsKarp::BFS(std::vector<edgeweight> &residFlow, std::vector<node
...
+    } while (!Q.empty());
+
+    return 0.0;
+}
+
+edgeweight EdmondsKarp::directedBFS(const std::vector<count> &reverseEdges,
+                                    std::vector<node> &pred) const {
+    std::fill(pred.begin(), pred.end(), none);
+    pred.resize(graph->upperNodeIdBound(), none);
+    std::vector<edgeweight> gain(graph->upperNodeIdBound(), std::numeric_limits<edgeweight>::max());
```
Comment (angriman) [inline networkit/cpp/flow/EdmondsKarp.cpp:63]: Since `directedBFS` might is called several times, I suggest having `gain` as a member variable of the class, so that we do not need to allocate space for it multiple times.

File: networkit/cpp/flow/EdmondsKarp.cpp [hunk 19]
```diff
@@ -18,7 +17,7 @@ namespace NetworKit {
 EdmondsKarp::EdmondsKarp(const Graph &graph, node source, node sink)
     : graph(&graph), source(source), sink(sink) {}
 
-edgeweight EdmondsKarp::BFS(std::vector<edgeweight> &residFlow, std::vector<node> &pred) const {
+edgeweight EdmondsKarp::BFS(std::vector<node> &pred) const {
     std::fill(pred.begin(), pred.end(), none);
     pred.resize(graph->upperNodeIdBound(), none);
     std::vector<edgeweight> gain(graph->upperNodeIdBound(), 0);
```
Comment (angriman) [inline networkit/cpp/flow/EdmondsKarp.cpp:23]: Same here.

**Review by angriman — COMMENTED** [review]
Thank you for addressing the comments. I left two last suggestions that should improve the performance. The rest looks good to me.

**Comment by CharJon** [comment]
@angriman @fabratu this PRs main intention was to fix the bugs and I tried to stay close to the original implementation. Regarding performance: There are definitely places that can be optimized further. Feel free to change them directly before merging.

**Review by angriman — APPROVED** [review]
