### PR TITLE
Initialize edgeID datastructure when constr. graph with indexed edges.

### LINKED ISSUE #986: Core dumped when adding weighted edges with edgesIndexed=True
Hello all, first issue here.

Decided I would report the following:
I have a dict mapping strings to node ids as well as a list of edges

    import networkit as nk

    nodes = {'Joe':0, 'Bob': 1, 'Sue': 2}  # 60 nodes approx.
    edges = [
        {"from":0, "to":1, "weight":  0.1231232329}, 
        {"from":1 ,"to": 2, "weight:" 123.413123627)
    ] # 2-3k edges approx.

    G = nk.Graph(n=len(nodes), weighted=True, directed=True, edgesIndexed=True)
    
    for edge in edges:
        G.addEdge(u=edge["from"], v=edge["to"], w=round(edge["weight"], 4))

results in:
    Segmentation fault (core dumped)

Tested the same logic with edgesIndexed=False and haven't yet encountered the core dump.
Also tried groupbyng my data by from, to in order to avoid multiEdges but still receive the error.

Perhaps there is some elementary logical error I'm making due to my lack of understanding in c++ and low-level memory management. Furthermore, this is my first ever issue so please be lenient.

Happy to provide more data as needed.

### PR DESCRIPTION
**Pull request by fabratu**
Fixes #986.

### CODE REVIEW

File: networkit/cpp/graph/test/GraphGTest.cpp [hunk 1]
```diff
@@ -132,6 +132,12 @@ void GraphGTest::SetUp() {
 
 /** CONSTRUCTORS **/
 
+TEST_F(GraphGTest, testDefaultConstructorIndexed) {
+    Graph G = Graph(3, false, false, true);
```
Comment (angriman) [inline networkit/cpp/graph/test/GraphGTest.cpp:136]:
```suggestion
    Graph G(3, false, false, true);
```

File: networkit/cpp/graph/test/GraphGTest.cpp [hunk 2]
```diff
@@ -132,6 +132,12 @@ void GraphGTest::SetUp() {
...
+    G.addEdge(0, 1);
+    ASSERT_EQ(0, G.edgeId(0, 1));
```
Comment (angriman) [inline networkit/cpp/graph/test/GraphGTest.cpp:138]: In this case it is better to use `EXPECT_EQ` (see https://testing.googleblog.com/2008/07/tott-expect-vs-assert.html). Also, avoid yoda conditions (https://en.wikipedia.org/wiki/Yoda_conditions)
```suggestion
    EXPECT_EQ(G.edgeId(0, 1), 0);
```

File: networkit/cpp/graph/test/GraphGTest.cpp [hunk 3]
```diff
@@ -132,6 +132,12 @@ void GraphGTest::SetUp() {
 
 /** CONSTRUCTORS **/
 
+TEST_F(GraphGTest, testDefaultConstructorIndexed) {
```
Comment (angriman) [inline networkit/cpp/graph/test/GraphGTest.cpp:135]: It seems that you have to use parametric tests:
```suggestion
TEST_P(GraphGTest, testDefaultConstructorIndexed) {
```

Comment (fabratu) [reply networkit/cpp/graph/test/GraphGTest.cpp:135]: Yeah, I am not sure why though. We are mixing TEST_F and TEST_P also in other test files (same syntax). Trying to find a way around it, otherwise the same test is repeated 4x.

File: networkit/cpp/graph/test/GraphGTest.cpp [hunk 4]
```diff
@@ -132,6 +132,12 @@ void GraphGTest::SetUp() {
 
 /** CONSTRUCTORS **/
 
+TEST(GraphGTest, testDefaultConstructorIndexed) {
+    Graph G(3, false, false, true);
```
Comment (angriman) [inline networkit/cpp/graph/test/GraphGTest.cpp:136]: Maybe test it for directed graphs as well?

Comment (fabratu) [reply networkit/cpp/graph/test/GraphGTest.cpp]: Good point.

File: networkit/cpp/graph/test/GraphGTest.cpp [hunk 5]
```diff
@@ -132,6 +132,18 @@ void GraphGTest::SetUp() {
 
 /** CONSTRUCTORS **/
 
+TEST(GraphGTest, testDefaultConstructorIndexed) {
```
Comment (angriman) [inline networkit/cpp/graph/test/GraphGTest.cpp:135]: I'd recommend to split this into two tests, one for directed and one for undirected graphs.
Test isolation is something that we could improve across the whole library.

Comment (fabratu) [reply networkit/cpp/graph/test/GraphGTest.cpp]: You are right. In my mind the test was too small to seperate it, but this more a decision about how we want to structure the tests.

**Review by angriman — APPROVED** [review]
