### PR TITLE
SpanningTree: bugfix suggestion and tests

### LINKED ISSUE #1002: Kruskal Spanning Tree Bug
The spanning tree code in `KruskalMSF` seems to have a bug for weighted graphs (intoduced with the merge from #873 ?).
As the testcases only cover unweighted graphs, none of them fails.
`sortedEdges` is empty when std::transform tries to run resulting in a segfault.

### PR DESCRIPTION
**Pull request by CharJon**
Fixes #1002

### CODE REVIEW

File: networkit/cpp/graph/KruskalMSF.cpp [hunk 1]
```diff
@@ -32,7 +32,7 @@ void KruskalMSF::run() {
         // sort edges in decreasing weight order
         std::vector<MyEdge> sortedEdges; // (m);
         std::transform(G->edgeWeightRange().begin(), G->edgeWeightRange().end(),
-                       sortedEdges.begin(), [](const auto &edge) -> MyEdge {
+                       std::back_inserter(sortedEdges), [](const auto &edge) -> MyEdge {
```
Comment (fabratu) [inline networkit/cpp/graph/KruskalMSF.cpp:35]: Since transform should work on already allocated memory, it might be beneficial performance-wise to pre-allocate the vector on definition.

**Review by fabratu — CHANGES_REQUESTED** [review]
Thanks for the PR! I have a minor change request, otherwise this looks fine.

File: networkit/cpp/graph/KruskalMSF.cpp (hunk 1 above)
Comment (CharJon) [reply networkit/cpp/graph/KruskalMSF.cpp:35]: Makes a lot of sense. Will take care of this.

**Comment by CharJon** [comment]
Is there something I could change to stop the pipeline from failing? I do not see why the checks pass on the main branch, but not on this one.

**Comment by fabratu** [comment]
> Is there something I could change to stop the pipeline from failing? I do not see why the checks pass on the main branch, but not on this one.

Most of the problems will be fixed with #1001 (plan is to have it in master shortly). I am not sure about the failing `DynBetweennessGTest.runDynVsStatic` test. However I would suggest re-running the tests after merge/rebase.

**Comment by fabratu** [comment]
#1001 is merged, you can now rebase.
